name: Gradle Package

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Generate Jacoco Report
        run: ./gradlew generateJacocoReport

      - name: Save Jacoco Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html # Ajusta la ruta según donde se genera tu informe

      - name: Check Jacoco Coverage
        id: jacoco-coverage
        run: |
          coverage=$(grep "Total" build/jacoco/test/html/index.html | grep -oP '\d+(?=%)')
          echo "Coverage: $coverage%"
          if (( coverage < 5 )); then
            echo "Coverage is less than 5%, failing the build."
            exit 1
          fi
        shell: bash

