name: Gradle Package

on:
  push:
    branches: [master]

jobs:
  check-secret:
    name: check-secret
    environment:
      name: productions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec version
          set +e 
          horusec start -p="./" -e="true" -o="json" -O=/horusec.json --disable-docker
          set -e
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: horusec
            path: horusec.json

  build:
    needs: check-secret
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Clean
        run: ./gradlew clean

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Run Test
        run: ./gradlew test

      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport

      - name: Run Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: false
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv



